# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openskills < Formula
  desc "AI editor extension manager — manage plugins, skills, and marketplaces across Codex, Claude, Cursor"
  homepage "https://github.com/lovelyJason/openskills"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lovelyJason/openskills/releases/download/v0.2.1/openskills_0.2.1_darwin_amd64.tar.gz"
      sha256 "5c1f5787a8e61bc5b530753953afe589f6961ae2f416de47e5a4ce2cc300da26"

      define_method(:install) do
        bin.install "openskills"
        bin.install_symlink "openskills" => "osk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lovelyJason/openskills/releases/download/v0.2.1/openskills_0.2.1_darwin_arm64.tar.gz"
      sha256 "f795356e4999dee94ff6d7ccad73b6303c5835756f96f1e23557027eb4a9ad73"

      define_method(:install) do
        bin.install "openskills"
        bin.install_symlink "openskills" => "osk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lovelyJason/openskills/releases/download/v0.2.1/openskills_0.2.1_linux_amd64.tar.gz"
      sha256 "b7cf98630dab7c6f4a0b95ab16fb08e811ee23623e7e2c7f31b62b30f8cbc081"
      define_method(:install) do
        bin.install "openskills"
        bin.install_symlink "openskills" => "osk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lovelyJason/openskills/releases/download/v0.2.1/openskills_0.2.1_linux_arm64.tar.gz"
      sha256 "9fc449d1cff4cb195ba4c49fdfb78cc957f7e899f570ea27ee75b76e6e278447"
      define_method(:install) do
        bin.install "openskills"
        bin.install_symlink "openskills" => "osk"
      end
    end
  end

  def caveats
    <<~EOS
      🛠️  openskills installed successfully!

      Short alias available: osk

      Get started:
        osk marketplace add <git-url>           # add a marketplace
        osk plugin list                          # browse plugins
        osk skill list                           # browse skills
        osk status                               # check system

      Docs: https://github.com/lovelyJason/openskills
    EOS
  end

  test do
    system "#{bin}/openskills", "--version"
  end
end
