# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openskills < Formula
  desc "AI editor extension manager — manage plugins, skills, and marketplaces across Codex, Claude, Cursor"
  homepage "https://github.com/lovelyJason/openskills"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lovelyJason/openskills/releases/download/v0.1.0/openskills_0.1.0_darwin_amd64.tar.gz"
      sha256 "71b69b68fe524da39e07660af5497348fdd03208b19c5fc3e6630ae2aa4f49ce"

      define_method(:install) do
        bin.install "openskills"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lovelyJason/openskills/releases/download/v0.1.0/openskills_0.1.0_darwin_arm64.tar.gz"
      sha256 "d213b28c9d0dfc23623bfa8650fa230943762f9c7dcd95dea6e77e5deead3adc"

      define_method(:install) do
        bin.install "openskills"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lovelyJason/openskills/releases/download/v0.1.0/openskills_0.1.0_linux_amd64.tar.gz"
      sha256 "d4d4b742e06097d53718629fca088100dee54d2ae5f1c0086aa91d33b1276d14"
      define_method(:install) do
        bin.install "openskills"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lovelyJason/openskills/releases/download/v0.1.0/openskills_0.1.0_linux_arm64.tar.gz"
      sha256 "7ae98624c050610d1644637d48142328879b3789a9189badf44ca185ff3edbfb"
      define_method(:install) do
        bin.install "openskills"
      end
    end
  end

  def install
    bin.install "openskills"
    bin.install_symlink "openskills" => "osk"
  end

  def caveats
    <<~EOS
      🛠️  openskills installed successfully!

      Short alias available: osk

      Get started:
        osk marketplace add <git-url>           # add a marketplace
        osk plugin list                          # browse plugins
        osk skill list                           # browse skills
        osk status                               # check system

      Docs: https://github.com/lovelyJason/openskills
    EOS
  end

  test do
    system "#{bin}/openskills", "--version"
  end
end
